[2017-02-03 Fri]

Program CLI wyświetlający pogodę na dany dzień lub prognozę na kilka
dni. Użycie web services udostępniających informacje o pogodzie.

* webserwisy pogodowe
  [2017-02-03 Fri]

Top 10 Weather APIs
https://www.programmableweb.com/news/top-10-weather-apis/analysis/2014/11/13

OpenWeatherMap
https://openweathermap.org/api

** City ID

City ID można używać w OpenWeatherMap - zamiast nazwy bo nazwa może
być niejednoznaczna.

- http://openweathermap.org/help/city_list.txt
- http://bulk.openweathermap.org/sample/city.list.json.gz

- https://openweathermap.desk.com/customer/portal/questions/8159618-city-id
- http://stackoverflow.com/questions/27883777/how-to-find-weather-forecast-city-id

* Rejestracja - API Key
  [2017-02-04 Sat]

Założenie konta w celu pobrania API Key
https://openweathermap.org/appid#get
- Username
- Email
- Password

Utworzenie repozytorium: github.com/adbr/pogoda

* Escape'owanie URLa
  [2017-02-14 Tue]

- linki
  - https://en.wikipedia.org/wiki/Query_string
  - https://en.wikipedia.org/wiki/URL_encoding
  - https://golang.org/pkg/net/url/

- URL wysyłany w requeście HTTP powinien być escape'owany
  (zakodowany) - niektóre znaki (specjalne) powinny być zakodowane
  przy użyciu sekwencji %HH

- Funkcja http.Get(urlStr) nie escape'uje URLa przekazanego jako
  argument - np. jeśli url (query w urlu) zawiera spację to zostanie
  zwrócony komunikat serwera:
  : 400 Bad Request

  Znaki UTF-8 też powinny być escape'owane, ale w przypadku
  openweathermap znaki UTF-8 nie muszą być zakodowane - nie powoduje
  to zwrócenia błędu - widocznie ten serwer akceptuje takie URLe.

- pakiet net/url zawiera funkcje do escape'owania URLi

* Result

Przykładowy wynik:

{
    "coord": {
        "lon": 19.92,
        "lat": 50.08
    },
    "weather": [
        {
            "id": 803,
            "main": "Clouds",
            "description": "broken clouds",
            "icon": "04n"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 275.15,
        "pressure": 1008,
        "humidity": 80,
        "temp_min": 275.15,
        "temp_max": 275.15
    },
    "visibility": 10000,
    "wind": {
        "speed": 1,
        "deg": 190
    },
    "clouds": {
        "all": 75
    },
    "dt": 1488405600,
    "sys": {
        "type": 1,
        "id": 5352,
        "message": 0.0436,
        "country": "PL",
        "sunrise": 1488345701,
        "sunset": 1488385441
    },
    "id": 3094802,
    "name": "Krakow",
    "cod": 200
}
